"""Creates Goal ID column.

Revision ID: 8ea97fe34c05
Revises: 8285fe6ed690
Create Date: 2024-11-06 18:14:51.758546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea97fe34c05'
down_revision = '8285fe6ed690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('task_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'goal', ['goal_id'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('task_author_id_fkey', 'goal', ['author_id'], ['id'])
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###
